name: Code Review Workflow

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  code_review:
    name: Code Review Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Echo code review checks start
        run: echo "Starting code review checks..."

      - name: Echo code review checks complete
        run: echo "Code review checks complete!"
